### PR TITLE
Add BBC root functions and test files to neonPlants

### PR DESCRIPTION
**Pull request by schafnoir**
Three functions developed and tested for addition to neonPlants package. The `rootChemJoin` function uses three BBC tables to join fine root chemistry data with dryMass data. The `rootMassStandardize` function harmonizes older data with deprecated sizeCategory and rootStatus values current data. The `rootMassScale` function combines field and lab data, and optionally dilution sampling data, to calculate root mass per unit area and root mass per unit soil volume. Each function has accompanying test data and test scripts using the `testthat` framework.

### CODE REVIEW

**Comment by schafnoir** [comment]
@sokole - let me know if I should request merging into a branch other than `neonPlants:dev`

**Comment by schafnoir** [comment]
FWIW, I am aware that these function names do not follow the `verbNoun` model, and I am not clear how strongly NEON as an organization feels about maintaining this model. One reason I elected to use `root` to start off each function name is so a user wanting to use a root function on root data can lead off with typing 'root'. However, RStudio does a good job of looking within function name strings so if we want to stick with `verbNoun` because we want to maintain consistency with neonUtilities functions, then I could envision renaming these functions like:

- rootChemJoin --> joinRootChem
- rootMassStandardize --> standardizeRootMass
- rootMassScale --> scaleRootMass

**Comment by schafnoir** [comment]
@sokole - Reading your feedback to Katie regarding using neonUtilities list objects as inputs, I did discuss the structure of inputs for these functions with Claire and it seemed a good idea to be able to use data downloaded from the Portal via the webUI. The text I've put together for the man pages illustrate use of neonUtilities list objects as the preferred inputs, and the functions all check for required columns and error out if they don't get them. Maybe we can discuss as a group with the other function authors because I think the flexibility of what these functions allow as inputs is useful.

**Comment by sokole** [comment]
@schafnoir happy to discuss it. The reasons we went the way we did with Dave's function for div were:

1. Stacking the tables for a given site/date window only made sense if we were certain the users had the complete dataset for all tables that they were trying to stack (i.e., the results would be nonsensical if they didn't include the same date ranges for all tables). It seemed the best way to enforce this was to make the users submit the unedited tables from the list returned by `neonUtilities`. 
2. We figured if someone downloaded data from the portal and wanted to load it into R, they would need to use neonUtilities to stack the data. I was assuming the stacking function creates the same list object as `loadByProduct`, but maybe that's incorrect? 

My guidance to Sam was similar for the biomass function because I think we also want to be able to assume the user is submitting a complete dataset. Same for Katie with the pheno functions. But maybe this shouldn't be the case for all these use cases?

**Comment by sokole** [comment]
> FWIW, I am aware that these function names do not follow the `verbNoun` model, and I am not clear how strongly NEON as an organization feels about maintaining this model. One reason I elected to use `root` to start off each function name is so a user wanting to use a root function on root data can lead off with typing 'root'. However, RStudio does a good job of looking within function name strings so if we want to stick with `verbNoun` because we want to maintain consistency with neonUtilities functions, then I could envision renaming these functions like:
> 
> * rootChemJoin --> joinRootChem
> * rootMassStandardize --> standardizeRootMass
> * rootMassScale --> scaleRootMass

Yeah, I've had similar thoughts about this. Now that we have candidate function names for several data products maybe we should all get together and discuss what is most intuitive. We only have one function that has been out in the world, so if we want to rethink our naming convention, now is a reasonable time.

**Comment by schafnoir** [comment]
@sokole - All three root functions have been updated following the discussion with function authors + Claire. Changes include:

- Names are consistent with `verbNoun` paradigm.
- List inputs are configured to be the default but table inputs are also allowed.
- Exception handling and testing has been added to deal with user errors with inputs (i.e., assigning a table to what should be a list).
- Test data has been trimmed to one site x eventID to minimize size of package.

Let me know if you see anything else out of order upon review!

**Pull request merged**
